### ISSUE TITLE
Decoding error with organizations endpoint

### ISSUE THREAD

**Issue by stout01** [Availity/availity-ekko#42]
When the browser goes to decode the response from the organizations endpoint, there is a decoding error.

![image](https://cloud.githubusercontent.com/assets/13242926/26414182/6075d6e4-407c-11e7-9984-dcc84914f8fe.png)

When trying to view the response in Fiddler, I receive this error:
![image](https://cloud.githubusercontent.com/assets/13242926/26414223/7efc4e90-407c-11e7-9840-0a6444013f71.png)

The issue is resolved after I remove the compression middleware.

**Comment by robmcguinness** [comment]
does this happen on other endpoints?

**Comment by stout01** [comment]
I have not experienced this on any other endpoints

**Comment by robmcguinness** [comment]
does this happen on other endpoints?

**Comment by KaseyPowers** [comment]
Playing around with this error. I thought it might be something in my json so I removed chunks until it worked. I think it is triggered instead by json files larger than some arbitrary threshold.

**Comment by robmcguinness** [comment]
Ekko uses Express and the `compression` middleware that has a threshold of `1k`.  i'm guessing the payloads with issue are the ones over `1k`.

**Comment by robmcguinness** [comment]
It appears this issue is not within **availity-ekko** but a bug in  **availity-workflow** proxy `contextRewrite` setting.  When  **ekko** responds with json, **workflow** tries to rewrite the URL within the body response to match the host.  During this process, **workflow** ends up corrupting the response body for gzipped contents.  By default any payload over `1k` is gzipped (under `1k` is not gzipped).

**Comment by robmcguinness** [comment]
Fixed https://github.com/Availity/availity-workflow/commit/acc69af856ae5dea9a3f8c551e33c3b93466e65f

**Comment by robmcguinness** [comment]
Fixes in `v2.1.1`.  Please `npm install availity-workflow@latest --save`
